### ISSUE TITLE
No devdocs-browser-list-docs?

### ISSUE THREAD

**Issue by mkleehammer** [blahgeek/emacs-devdocs-browser#1]
This is one of the best new elisp packages in a while!   One more reason to not have to leave Emacs :)

Not important, but I notice the readme states there is a list-docs function but there doesn't seem to be.

Thanks for the great package.

**Comment by blahgeek** [comment]
Glad you like it! There is this function: https://github.com/blahgeek/emacs-devdocs-browser/blob/950eb9fa5fe0be59d3047fe6d547942bf0e39c2c/devdocs-browser.el#L356, it's just not an interactive command. (I don't think users would need to call this interactively? If you want, you can do `M-: devdocs-browser-list-docs`)

**Comment by hrehfeld** [comment]
Confused me as well.
