### ISSUE TITLE
Performance issue about `devdocs-browser-open`

### ISSUE THREAD

**Issue by condy0919** [blahgeek/emacs-devdocs-browser#2]
``` elisp
(benchmark 10 '(let ((unread-command-events '(?v ?e ?c ?t ?o ?r ? ?a ?t 13)))
                 (call-interactively #'devdocs-browser-open)))
;; Elapsed time: 4.153758s
```
benchmarked on a cpp file, it takes 0.4s per call. Perhaps caching the last rows will help a lot.

**Comment by blahgeek** [comment]
Hi!

Can you try the latest master to see if it solved your issue? https://github.com/blahgeek/emacs-devdocs-browser/commit/0a6cc53b7af236598fa9d86a618740830d088c0a this commit fixed a major performance regression.

**Comment by condy0919** [comment]
Thanks, resolved.
