### ISSUE TITLE
Tuning the devdocs lookup to be more accurate 

### ISSUE THREAD

**Issue by rileyrg** [blahgeek/emacs-devdocs-browser#7]
I'm not sure of the best approach here, but if if my cursor is on Number in a typescript file and I call devdocs-browser-open it would be nice if it found "Number" in the docs and not "errors cant convert BigInt to number" ;)  Im using the devdocs-browser-major-mode-docs-alist to map typescript-mode to the typescript devdocs btw.  If I type "Number" in the prompt then it finds it fine. Using consult btw : could this be the issue?

**Comment by blahgeek** [comment]
Thanks for you report.

Currently `devdocs-browser-open` merely use the symbol at cursor as the default input for `completing-read`, nothing fancy. To achieve what you described, it needs to understand the code in a language-specific way that it's a "Number" under cursor, which would not be possible currently. Maybe using infos provided by language server or treesitter would make this possible, but still not trivial.

So I don't this this can be supported for now.
